filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.modules:
  - module: mysql
    slowlog:
      enabled: true
      var.paths: ["/var/log/mysql/mysql-slow.log"]

setup.dashboard.enabled: true

setup.kibana.host: "http://kibana:5601"

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  username: "elastic"
  password: "hsa13"
