spring:
  datasource:
    url: jdbc:h2:file:./data/test-h2
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    hibernate:
      ddl-auto: create

    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
logging:
  config: classpath:log4j2-test.xml
