---
version: '3.8'

networks:
  frontend:
    driver: ${NETWORKS_DRIVER}
  backend:
    driver: ${NETWORKS_DRIVER}
volumes:
  redis-master:
    driver: ${VOLUMES_DRIVER}
  redis-slave:
    driver: ${VOLUMES_DRIVER}
services:
  redis-master:
    build:
      context: ./docker/redis
    container_name: redis-master
    volumes:
      - ./volume/data/redis-master:/data
    ports:
      - "6379:6379"
    networks:
      - backend
  redis-slave:
    image: redis:latest
    container_name: redis-slave
    command: "redis-server --slaveof redis-master 6379"
    volumes:
      - ./volume/data/redis-slave:/data
    ports:
      - "6380:6379"
    depends_on:
      - "redis-master"
    networks:
      - backend
  php-fpm:
    build:
      context: ./docker/php-fpm
    container_name: php-fpm
    depends_on:
      - redis-master
      - redis-slave
    environment:
      - REDIS_HOST=redis-master
      - REDIS_PORT=6379
      - APP_ENV=dev
    expose:
      - "9000"
    volumes:
      - ./application:/var/www/html
    networks:
      - backend
  nginx:
    build:
      context: ./docker/nginx
      args:
        - PHP_UPSTREAM_CONTAINER=php-fpm
        - PHP_UPSTREAM_PORT=9000
    container_name: nginx
    restart: always
    volumes:
      - ./application:/var/www/html
      - ./docker/nginx/sites-available:/etc/nginx/sites-available
      - ./volume/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "8080:80"
    networks:
      - backend
      - frontend
