---
version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cache:/data/nginx/cache
      - ./images:/data/images
      - ./html:/data/www
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443
