---
version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./cache:/data/nginx/cache
    ports:
      - 80:80
    links:
      - app
  app:
    image: nginx:latest
    container_name: app
    volumes:
      - ./app.conf:/etc/nginx/nginx.conf
      - ./images:/data/images
      - ./html:/data/www
    ports:
      - 8080:80
