---
version: '3.8'

networks:
  backend_subnetwork:
    ipam:
      driver: ${NETWORKS_DRIVER}
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
volumes:
  influxdb:
    driver: ${VOLUMES_DRIVER}
services:
  attacker:
    build: ./docker/blackarch
    container_name: attacker
    networks:
      backend_subnetwork:
        ipv4_address: 172.16.238.10
  #Defender without DDoS protection
  defender-0:
    build: ./docker/nginx
    container_name: defender-0
    restart: always
    volumes:
      - ./docker/nginx/nginx.default.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-available/default.conf:/etc/nginx/sites-available/default.conf
      - ./docker/nginx/website:/var/www/html
      - ./volume/logs/defender-0:/var/log/nginx
    ports:
      - "${DEFENDER_0_HTTP_PORT}:80"
    networks:
      backend_subnetwork:
        ipv4_address: 172.16.238.20
  #Defender with DDoS protection
  defender-1:
    build: ./docker/nginx
    container_name: defender-1
    restart: always
    environment:
      - TWEAK_IPTABLES=true
    volumes:
      - ./docker/nginx/nginx.protected.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites-available/protected.conf:/etc/nginx/sites-available/default.conf
      - ./docker/nginx/website:/var/www/html
      - ./volume/logs/defender-1:/var/log/nginx
    ports:
      - "${DEFENDER_1_HTTP_PORT}:80"
    networks:
      backend_subnetwork:
        ipv4_address: 172.16.238.30
